version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.1

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:erbium

jobs:
  build:
    <<: *defaults

    steps:
      - checkout
      - run: ./build.sh
      - persist_to_workspace:
          root: ~/repo
          paths: .

  webtests:
    working_directory: ~/repo
    docker:
      - image: circleci/openjdk:8-jdk-browsers

    steps:
      - attach_workspace:
          at: ~/repo
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Xvfb install
          command: sudo apt-get --assume-yes --quiet --no-install-suggests --no-install-recommends install xvfb
      - run:
          command: |
            google-chrome --version
            chromedriver --version
          name: Check install
      - run: cd webtests && xvfb mvn clean install -Dwebdriver.chrome.driver=/usr/local/bin/chromedriver

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: ./deploy.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
      - webtests :
          requires:
            - build
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /\d+\.\d+\.\d+/
            branches:
              ignore: /.*/

